// Generated by CoffeeScript 1.7.1
(function() {
  var Car, VW,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Car = (function() {
    function Car(name) {
      this.name = name;
    }

    Car.prototype.mil = 8100;

    Car.prototype.changeName = function(name) {
      this.name = name != null ? name : 'default';
    };

    return Car;

  })();

  VW = (function(_super) {
    __extends(VW, _super);

    function VW() {
      return VW.__super__.constructor.apply(this, arguments);
    }

    return VW;

  })(Car);

  car('VW');

}).call(this);

//# sourceMappingURL=classCoffe.map
