// Generated by CoffeeScript 1.7.1
(function() {
  var beer, food, html, there, _i, _len, _ref;

  _ref = ['a', 'b', 'c'];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    food = _ref[_i];
    console.log(food);
  }

  beer = "Hello";

  there = "" + beer + " There";

  console.log(there);

  html = "<p>\n  Hello world!\n</p>";

  console.log(html);

}).call(this);

//# sourceMappingURL=food.map
